# Generated by Django 5.2.1 on 2025-06-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chat', '0002_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
